import GUI.Plugins.SketchSelect
import GUI.Plugins.SketchLineDraw
import GUI.Plugins.SketchSplineDraw
import GUI.Plugins.SketchArcDraw
import GUI.Plugins.SketchCircleDraw
import GUI.Plugins.SketchFilletDraw
import GUI.Plugins.SketchTextDraw
import GUI.Plugins.SketchAttributeDraw
import GUI.Plugins.SketchGenerateAreas
import GUI.Plugins.SketchCreateArea
import GUI.Plugins.SketchCreateCompositeArea
import GUI.Plugins.SketchScale
import GUI.Plugins.SketchPattern
import GUI.Plugins.SketchParametry
import GUI.Plugins.GenericView